services:
  bot:
    build: ./app
    restart: always
    command: tail -f main.py
    volumes:
      - ./app/:/opt/projects/app/
      - ./logs/:/opt/projects/app/logs/
    env_file:
      - ./.env/dev.env
    depends_on:
      - db

  db:
    image: mongo:7.0
    restart: always
    volumes:
      - ./database:/data/db
    command: --quiet
    ports:
      - 127.0.0.1:27025:27017
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin --quiet | grep 1
      interval: 60s
      timeout: 60s
      retries: 6
