name: Build and Deploy to Production

on:
  push:
    branches: ["feature/cicd"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Login Docker"
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}"

      - name: Build Docker image
        run: docker build -t ${{ secrets.IMAGE_REGISTRY }}:${{ vars.IMAGE_NAME }} -f ./app/Dockerfile ./app

      - name: Push to Registry
        run: docker push ${{ secrets.IMAGE_REGISTRY }}:${{ vars.IMAGE_NAME }}
